//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestucture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleMovimiento
    {
        public int consMovimiento { get; set; }
        public int codProducto { get; set; }
        public int idUbicacion { get; set; }
        public int cantidad { get; set; }
    
        public virtual encabezadoMovimiento encabezadoMovimiento { get; set; }
        public virtual posicion posicion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
