//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestucture.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sisurEntities : DbContext
    {
        public sisurEntities()
            : base("name=sisurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<detalleMovimiento> detalleMovimiento { get; set; }
        public virtual DbSet<encabezadoMovimiento> encabezadoMovimiento { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<movimientoTipo> movimientoTipo { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<posicion> posicion { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
    }
}
